### ISSUE TITLE
Bugged gallery ex links

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#10]
I had some galleries (links in the thread) that would not update properly after entering the correct links and trying the auto search multiple times.

It seems if the gallery already has an link and you enter that same link in again it won't try to update and if you do the auto-search it is probably skipping the gallery because it already has a link. So the only way to fix a bugged gallery/link is to enter an incorrect link (causes PandaViewer to crash) then enter the correct link again then it will finally update properly.

Also trying to remove the link and save it doesn't do anything the link remains.

**Comment by seanegoodwin** [comment]
>It seems if the gallery already has an link and you enter that same link in again it won't try to update and if you do the auto-search it is probably skipping the gallery because it already has a link. 

This is correct. I'm wondering why you want to re download the metadata. Is there a reason for this?

>Also trying to remove the link and save it doesn't do anything the link remains.

Fixed in the next release.

**Comment by Black-Light** [comment]
>This is correct. I'm wondering why you want to re download the metadata. Is there a reason for this?
The metadata didn't download properly the 3 gallerys had no tags or ratings and doing an auto search didn't achieve anything. Also rying to edit in the correct link again (the gallery already had it) didn't do anything either. Thus i had to enter a false link and then enter a correct link again to fix this issue, I have only had it happen on 3 galleries so far and am unsure if it is just a problem with those galleries or something else.

**Comment by Black-Light** [comment]
As an update fixing links for galleries is much easier when they are in folders now, however fixing links for galleries that are archived seems impossible.

To fix galleries in a folder you can simply remove the link > save > add new link, for archived galleries this doesn't work even after removing the link and pressing save it still remains.

**Comment by Black-Light** [comment]
Titles now update properly and you can now remove links too!
