### ISSUE TITLE
Navagation (sorting and changing page) bug

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#11]
Sometimes a few (I have seen 3-7) galleries remain 'stuck' at the top of the gallery list despite being on a page that doesn't have that gallery. For instance making a search, changing the page or doing a sort and the first few galleries are stuck at the top.

It seems like when you navigate to a page with one of those 'stuck' galleries that gallery will fix itself and return to its normal position (just a guess here).

The rest of the entries sort, change page and search correctly,  I uploaded a webm on the thread if this is hard to understand. I think this bug is caused by searching but i am not completely sure.

**Comment by seanegoodwin** [comment]
I suspect this is also fixed in the latest version (it's available now).
If you see this again, let me know.
