### ISSUE TITLE
0.5 Incorrect scaling

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#13]
Something is wonky with the new versions scaling as seen below, doesn't seem to be tied to desktop resolution or window width/height. Sadly this makes 0.5 pretty hard to use and I'm going to stick to the old version until it's fixed.

Comparison:

Panda Dev
![comparison](https://cloud.githubusercontent.com/assets/1712653/8322404/8a8ba3c0-1a02-11e5-8c75-28bc421300d5.png)

Mine
![comparison](https://cloud.githubusercontent.com/assets/1927256/8322608/5a41b982-1a77-11e5-9001-8ab0de8bc286.png)
Because this was a bug I removed it from the feedback/suggestion issue.

**Comment by seanegoodwin** [comment]
Should be fixed in the new version.
