### ISSUE TITLE
[Feature Request][Minor] Support for decimal rating system used by ex average rating score

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#15]
Would be nice to have support for the full rating values presented on ex rather then just full and half stars. This way sorting by rating would be much more useful, there doesn't need to be a change in the icons just a mouse over that shows the value under the tool-tip or next to the stars.

**Comment by seanegoodwin** [comment]
What do you mean, "the full rating values"? The values on Ex are 0-5.

**Comment by Black-Light** [comment]
While you can only do a vote for 0-5 stars (including half stars) ex shows the average rating as a decimal value this is what i was referring to.

**Comment by seanegoodwin** [comment]
Should be in the new version.
