### ISSUE TITLE
[Feature Request][Minor] Select archive in explorer when using "Open In Folder"

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#16]
For users that don't have many sub folders and keep galleries archived the current open in folder option isn't very useful. To fix this it is would be great if PandaViewer selected the archive as well making it much easier to find.

Not sure if this would be helpful but I believe the windows command was something like this
**explorer.exe /select,"C:\Panda\gallery.zip"**

**Comment by seanegoodwin** [comment]
Added in the next release.
