### ISSUE TITLE
Missing thumbnails on some galleries (added after 0.5)

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#17]
This issue seems to be related to the images aspect ratio as i have had it happen when the first image is small (478 x 629) and large (2175 x 2998). However resizing the later to 50% of it's size (1088 x 1499) fixed this issue.

**Comment by seanegoodwin** [comment]
I added code to rotate an image that was longer than it was wide. I'm guessing that is causing the problem somehow. If can't reproduce this issue myself I'll probably just remove it.

**Comment by Black-Light** [comment]
I just found this happens to almost every gallery after I relocate its folder, now i'm not sure if it even was tied to the aspect ratio. renaming images that were broken seems to fix them.

**Comment by Black-Light** [comment]
Confirmed fixed in 0.5.3
