### ISSUE TITLE
Open GL error on launch (0.5.2)

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#18]
When launching PandaViewer i get an error which prevents me from using this version.
![untitled-1](https://cloud.githubusercontent.com/assets/1927256/8510576/7008e504-232f-11e5-82b1-a01c9d4df455.png)

**Update**
As seen in the error Panda Viewer wants these three libraries:
libEGL.dll
libGLESv2.dll
d3dcompiler_*.dll

However only libGLESv2.dll is present in the new version, I copied the two missing libraries found in 0.5.1.2 test and it works!

**Comment by seanegoodwin** [comment]
Whoops. I'll make sure to include those.
