### ISSUE TITLE
[Feature Request][Minor] Set as default functionality for sorting and search filters

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#21]
This would be pretty handy, every time I open PandaViewer I change the sorting to Date - Descending, you could even add this feature to the search filters for instance someone might want to only show translated galleries.

**Comment by Meowmel** [comment]
I would second a "remember sorting" option.

**Comment by seanegoodwin** [comment]
I'll probably just make it so it remembers your last sorting choice, and not add a separate box or anything. That work ok?

**Comment by Black-Light** [comment]
Yeah that would be fine, a check box in the sorting options window would be best if it's not too hard, remembering search filters wont be too important for most users I just thought I would suggest it if you had some time and thought it was worth implementing.

**Comment by seanegoodwin** [comment]
Newest version automatically saves sort settings.
