### ISSUE TITLE
[Opinion] No definite gallery found, picking first title result.

### ISSUE THREAD

**Issue by Triskov** [seanegoodwin/PandaViewer#23]
The following applies to: Version 0.5.3

I recently finished going through a lot of manga and doujinshi and added a lot to what I’m keeping. I ran the metadata collection again and then looked through to see what errors occurred. After cross-referencing several of the misnamed and mistagged galleries, they seem to be the result of the following:  No definite gallery found, picking first title result.

The problem is that when it is used, it seems to pick similarly named, but entirely different works. If the gallery is misnamed and mistagged, this is a loss in utility because then searching for it is no longer viable. This seems to mostly occur for galleries that have been purged, which means they cannot be found regardless. I don’t how often it picks the correct gallery overall, but looking through the logs, it does pick the correct gallery sometimes. 

I personally think that it should not be used because it will create an unknown amount of problems depending on the individual’s collection that won’t be immediately obvious.  I’d rather have 10 go untagged than then to have 10 that wouldn’t have been otherwise tagged without it, if it also incorrectly names and tags 10 galleries. It’s far easier to find those that had no results than those that were given incorrect results. Though, I have no idea of the ratio between correctly chosen and incorrectly chosen.

It wouldn’t be quite as much of a problem if only the names without thumbnails were shown in list format for easy checking, or if a list of the names could be generated and output to a text file which then could be checked, but that would only help with the very obvious.  Another way to mitigate the errors would be to blacklist the artists from being searched on exhentai if they are known to be purged, because of Wani and others. 

Of the ones not tagged at all, ~2 pages in this case, I don’t think any of them are on exhentai, so they were appropriately not renamed or tagged.
 
Overall, it works well.  

Honestly, if you remove that gallery-choosing decision, what I’d do is delete all the metadata and then run it again, because it’s simply too much of a pain and bothersome to search through all the galleries as is for incorrect ones and correct them. 

I also saw:
No definite gallery found, picking first insersection result
Which I assume is supposed to be “intersection” or “intersecting”. 
When I cross-referenced them, from what the ones I checked, there weren’t any mistakes, but I don’t know overall. 

A Few examples (I only went through a few pages then quit looking):
First is what I have it named as, second is the result it decided upon.

[Homunculus] Pay By Love
[Ikoma Ippei] a secret love affair and pay a visit (Korean)

[Tsukino Jyogi] Afterschool
[Okuni Yoshinobu] After School Tin Time chapter 1-4 [English] =SW=

[Kase Daiki] Consolation
(Akatsuki no Utage 4) [Nantoka Ikitemasu. (Megumiya)] Akirame no Uta. | Song of Consolation (Touhou Project) [English] {Gaku Gaku Animal Land}

[Homunculus] The Fitting Crisis
animation illustration2 

[Denki Shougun] Trap Trap
(JJFrenchie) Convention Trap/Cosplay Boy

[Ashiomi Masato] Face On
Free Hugs! Facehuggers for everyone.

[Henreader] Eyecatch
High School DXD BorN eyecatches

[Meme50] Chome Chome Otome - Girl Is Ready for XXX!
Hi-Res Cover Collection

[Shoot The Moon] Fukuyama-san 3 – Eruption
my galery ass 3

**Comment by seanegoodwin** [comment]
I went ahead and axed title searching in the new release. I'll keep this open for a bit to see if anyone else has any thoughts.

**Comment by seanegoodwin** [comment]
I went ahead and removed the title searching, it's not worth the trouble of dealing with.
