### ISSUE TITLE
[Minor] Duplicate Thumbnails/Info shown

### ISSUE THREAD

**Issue by Triskov** [seanegoodwin/PandaViewer#24]
It isn't a problem, but I now have a few where it has two of the same thumbnail and info side by side with each other. No, I don't have actual duplicates, they both open the same folder.
It's a benign mystery.

**Comment by seanegoodwin** [comment]
Can you email me a copy of your database? It can be found at C:/Users/<USER>/.lsv/db.sqlite. Email is didyouexpectarealemail@gmail.com

**Comment by Triskov** [comment]
Sent

**Comment by seanegoodwin** [comment]
The opengl problem you reported is fixed. I'm not entirely sure of the cause of this problem, but it might be fixed in the newest version. Can you give it a try?

**Comment by Triskov** [comment]
It wasn't fixed in the newest version, but I deleted the thumbnails and database to start anew and it was no longer present. I'll run to collect the metadata again later today.
