### ISSUE TITLE
[Feature Request] Hashes of galleries in a dedicated server

### ISSUE THREAD

**Issue by S0X-LT** [seanegoodwin/PandaViewer#25]
So as to not overload EH/EX and avoid the risk of getting banned.

Basically it would require one master account, preferably with access to most if not all galleries. 

The server-based PandaViewer Hash Archive should be capable of receiving hash request from clients and send it to the client if available faster than directly requesting to EH/EX, or requesting it from EH/EX directly if not available, albeit in a slower manner to avoid getting the master account banned, and having a queue to avoid overloading the server.

The server could also "technically" bypass the banned content from EH/EX (mainly Wani stuff); as it doesn't store images, but to do so it would have to request said gallery hash from another site, or uploading the gallery hash oneself (from RAW/scanlation source) and manually tag it.

It should also have a method to filter languages/tags from requests, but don't know if this is doable.

And of course, having a moderation crew to assure the correct function of the site and proper gallery tagging.

Thoughts?

**Comment by Black-Light** [comment]
I would much prefer a local solution maybe include this as a separate download, I'm not sure how hard it would be to keep something like this updated but if this is a realistic goal it would be an excellent addition to this program and would probably be useful for other projects as well. As such it might be better to manage this in a separate project.

**Comment by seanegoodwin** [comment]
If anything like this were to be implemented it would definitely be as a separate download - I'm not looking into having any hosting related to this project (that's a can of worms I'd rather not deal with). 

The largest problem I can see with this is that EX does not expose hashes via the API at all, so the crawled database would not have access to them either. We'd be limited to searching via the title (and potentially the file count as another identifying factor) which has not been very reliable historically.

**Comment by Black-Light** [comment]
Perhaps some of the staff could help with this

**Comment by seanegoodwin** [comment]
PandaViewer now provides an optional database full of EX metadata. It doesn't contain hashes, but I consider this feature (mostly) done.
