### ISSUE TITLE
[Feature Request] Update gallery tags feature

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#28]
It would be really nice to have a feature that can re-scan galleries (using the already provided ex-link) that already have tags/ratings, this would be useful for new galleries that are lacking tags, fixing incorrect tags and updating old galleries that are not using the new namespace tags.

While the new namespace feature is great, I currently have 10 pages of galleries missing these tags and it would be great to be able to easily fix them.

**Comment by seanegoodwin** [comment]
Added a checkbox to redownload all metadata in the download dialog.

**Comment by Black-Light** [comment]
Does this update use the links currently provided or try and search for galleries again?

**Comment by seanegoodwin** [comment]
It uses the links provided.

**Comment by Black-Light** [comment]
That was quick, thanks.
