### ISSUE TITLE
can't remove folders from being monitored..

### ISSUE THREAD

**Issue by kunikomithra** [seanegoodwin/PandaViewer#3]
i created a test folder and now i can't remove it from being monitored, i even removed the folder from my hard drive but for whatever reason its still in the application

i believe the watch folder settings is a little bit buggy, i'm usng the latest version

**Comment by seanegoodwin** [comment]
Mentioned this on the thread, but commenting here anyway.

The current model is once a gallery has been added to the database, it will be shown regardless of the parent directory's status (as long as the path to the gallery actually still exists).

Obviously this creates a bit of confusion for users. In the next release, we will filter out galleries that aren't in one of the currently saved folders.
