### ISSUE TITLE
[BUG][0.5.5] Attempt to read ZIP archive that was already closed

### ISSUE THREAD

**Issue by awused** [seanegoodwin/PandaViewer#30]
0.5.5 on Windows 7x64 fails to handle zip files with error:

ZipGallery.archive ERROR Failed to complete archive op for C:\Y\archive.zip
Traceback (most recent call last):
  File "C:\X\PandaViewer\Gallery.py", line 647, in archive
  File "C:\X\PandaViewer\Gallery.py", line 603, in raw_image
  File "C:\Python34\lib\zipfile.py", line 1132, in open
RuntimeError: Attempt to read ZIP archive that was already closed
UnknownArchiveError ERROR UnknownArchiveError raised with message Sorry, the archive file you tried to access is unable to be opened..
Details: 

The error is identical for every file.

0.5.4 handles the same files correctly. I attempted to build PandaViewer from source but gave up so I can't give you more detailed information.

**Comment by seanegoodwin** [comment]
Sorry about that, should be fixed in the latest version.
