### ISSUE TITLE
[Feature Request] Mark Exh as incorrect, clear info, and prevent it from fetching in the future

### ISSUE THREAD

**Issue by awused** [seanegoodwin/PandaViewer#32]
I've got more than a few archives that Pandaviewer picked completely random, unrelated, galleries for and I'd like to be able to just wipe the slate clean for that archive and clear the Exh link permanently.

Some of these have been taken down from Exh so I don't even have anything valid to put in that field, and it and the Custom Title fields keep repopulating themselves no matter what I try, short of going into the database myself.

**Comment by Triskov** [comment]
If you want to delete it all, go to C://users/your account/.lsv and delete the db.sqlite file in there. 
That'll delete all the metadata. That's what I did after "pick first title" was removed as I said I was going to do.

**Comment by awused** [comment]
That's unhelpful. I'd like to be able to clear metadata for individual galleries without nuking the whole thing or having to muck around in sqlite for each one. Frankly, the fact that deleting the contents of the "ExH URL" field in the UI and saving the gallery doesn't actually clear the URL from the metadata is either a huge oversight or a bug.

But it would be nicer to have an explicit per-gallery flag I can set to prevent PandaViewer from ever trying to automatically pair it with a gallery on Exh.

Likewise for clearing out a "custom" title to go back to the default.

**Comment by seanegoodwin** [comment]
>huge oversight or a bug.
Bug. It's fixed in the next version. Thanks for letting me know. As for the topic at hand, I've added a switch to the customize galleries page to allow you disable automatic metadata collection. 

>Likewise for clearing out a "custom" title to go back to the default.
You can just delete the custom title, it should revert to either the EX title or the file from the folder/archive it was generated from.

**Comment by awused** [comment]
> You can just delete the custom title, it should revert to either the EX title or the file from the folder/archive it was generated from.

Part of the problem was that it was defaulting back to the Exh gallery title. Since I couldn't clear the Exh URL so I had to go find the archive in one of my incredibly disorganized directories while I couldn't remember the correct title or artist.

**Comment by seanegoodwin** [comment]
Makes sense. Obviously that will be a non-issue with that bug fixed.

**Comment by seanegoodwin** [comment]
Closing, feature is available in the newest release.
