### ISSUE TITLE
[Feature Request] Delete confirmation dialog

### ISSUE THREAD

**Issue by awused** [seanegoodwin/PandaViewer#34]
I store my collection on a networked drive with no recycle bin or easy way of restoring deleted files. I'd really appreciate a confirmation dialog or, failing that, moving the delete option to the gallery's info page as a separate button.

Deleting archives is probably a rare enough action that this won't add too much annoyance to most people's daily usage.

**Comment by Meowmel** [comment]
> moving the delete option to the gallery's info page as a separate button.

Have mercy, don't do this to me. One of the main reasons I use PV for is to delete unwanted stuff and right now it's easy and fast. But in your case a confirmation dialog wouldn't be to bad, preferably with a "remember option" so I can continue to just delete away. ;)

**Comment by awused** [comment]
My issue is that it's one little mis-click between "open folder" and "view on ex" and then your file is instantly gone with no confirmation. I do have local backups I can restore from pretty quickly but that's a real pain.

A "remember" option is fine, then the user is making a choice to do without the safety net, though then you also need an option to re-enable it in the settings menu.

**Comment by seanegoodwin** [comment]
It's worth noting that any files that are "deleted" go to the Recycling bin - they're not deleted outright. 

But I agree there should be some safeguard. I'm thinking a "confirm before delete option that can be turned on/off in the settings menu.

**Comment by awused** [comment]
Not if they're on a NAS, which probably isn't horrifically uncommon, or running on Linux or another OS without a safety net.

**Comment by seanegoodwin** [comment]
Available in the newest version. You can disable the confirmation in the settings.
