### ISSUE TITLE
[Feature Request] Open comic book archives in comic reader

### ISSUE THREAD

**Issue by LoLsAlEd** [seanegoodwin/PandaViewer#37]
I love Panda Viewer, but the main thing that is holding me back from using it, is that the program opens all of my manga (which is stored in .cbz format) in the default image viewer when in actual fact I want to open it in my comic reader. 

I hope you can add this feature and thanks for the great program!

**Comment by seanegoodwin** [comment]
Sure, I'll work on getting this in as an option.

**Comment by seanegoodwin** [comment]
Added in the newest version. You'll want to go to the settings page and uncheck the extract cbz (maybe cbr too) option.

**Comment by LoLsAlEd** [comment]
Thanks for implementing this and great job on the program!
