### ISSUE TITLE
Page numbers and the go-to button

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#40]
Navigating pages in PV is a bit confusing as you have to remember what page you are on as it won't display this information anywhere. The work-around is to keep using the go-to function but this is slow and annoying. I suggest changing the button icon to instead display the current page number, I also had an issue where I had to select the text-field every time I wanted to enter in a page number but it doesn't seem to be happening anymore.

Unrelated but the toolbar height could be reduced by around 25% figured I would mention it now since you might be changing the icon.

**Comment by seanegoodwin** [comment]
For now, I've simply added the page numbers to the titlebar of the program. I'll probably try to think of something nicer, but at least you can see it now. 

I also made the popup's input be auto-selected. I plan on replacing the dropdown completely, but will have to wait.
