### ISSUE TITLE
ExHentai Hashing "wrong" Cover

### ISSUE THREAD

**Issue by Zuescho** [seanegoodwin/PandaViewer#41]
Hi, first off I love this thing and it works really great I used it to scan 1 Terabyte and it worked without problems.

My problem right now is that as a example i downloaded many files from hentairules, he includes his "cover" in those .rar archives.
Here is a example :
http://i.imgur.com/GnQxXA3.jpg

Now I found out that somebody uploaded it to exhentai http://exhentai.org/g/515677/b325009568/?p=4 (Oliver himself^^)

The problem is now that he hashed the "cover" from hentairules and saw that it exist and used it as a match, which is right from the idea but I guess you see my problem.

Do you have an idea how this could be changed?
One way would be to just blacklist that archive but then if this happens more often you had to blacklist a bunch of those.
Maybe just blacklist that hash?, I mean he uses the same cover for all releases so blacklisting it would not be a big problem.

Would love to here your thoughts.

**Comment by seanegoodwin** [comment]
Blacklisting might be the best way to deal with this - either the hash or the filename (I'm assuming it's something like credits.jpg).

Could you email me a link to where I could download one of these? Email is didyouexpectarealemail@gmail.com

**Comment by seanegoodwin** [comment]
Also, please refrain from using the duplicate deleting feature for now. This actually exposed an issue with how I calculate duplicates and your collection would have massive problems with it as it is.

**Comment by Zuescho** [comment]
Send it to you, hope it helps.

**Comment by seanegoodwin** [comment]
Should be fixed in the latest version. If you see more of these "banner" things, send them to me and I'll add them to the blacklist.

**Comment by Zuescho** [comment]
I will rescan my collection, this will take some time. After that i will report back here and give you feedback.
Thanks for the fast change and communication.

**Comment by Zuescho** [comment]
Hi, its me again.
Funny story... i just now saw that some of the banners are .png files... so the .jpg are now filtered which worked great, could you please include also the .png's

**Comment by seanegoodwin** [comment]
Should filter independent of file extension now.
