### ISSUE TITLE
Thumbnail isn't always the first image in a folder.

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#42]
I keep running into this issue, it seems like the way PV finds the first image in a folder is different then how windows does it's sorting resulting in PV opening and displaying the wrong image.

Windows:
0000cover.jpg
000.jpg
001.jpg

PandaViewer
000.jpg
0000cover.jpg
001.jpg

PV will always show the second image as a thumbnail instead, It's easy to fix this by renaming the images to the example below however it's a bit tedious.

000a.jpg
000b.jpg
001.jpg

**Comment by seanegoodwin** [comment]
You can manually change the thumbnail of a gallery by going to the info
screen and clicking on the image icon in the top bar.

Emulating the windows sorting algo is something I've wanted to do, but I
haven't been able to get the kinks out. Most natural sorting algos would
not order 0000cover before 000.
That said, it's still something I'd like to get in.

**Comment by Black-Light** [comment]
Yeah I realize you can change the image used in PV but this is still something that i would like to see fixed at least on the windows builds since it is a bit confusing until you realize why it's happening and how to fix it. I guess if Mac/Linux does the sorting differently and you decide to do builds for that it might get annoying to have to work between the two.

**Comment by seanegoodwin** [comment]
Turns out I can call the exact same function that explorer uses to sort. It obviously only works on windows, but other platforms have a different sorting mechanism anyway. Should be implemented in the next release.

**Comment by Black-Light** [comment]
This is actually still an issue, I had a files like this in windows
0000cover.jpg
000.jpg
001.jpg

But Panda Viewer saw 000.jpg first.
