### ISSUE TITLE
0.7.1 and 0.7 Won't launch

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#43]
The window doesn't even open and I don't get a log file, PV appears in task manager for 2-3 seconds then disappears.

Windows 7 x64

**Comment by Triskov** [comment]
Same for me.

**Comment by seanegoodwin** [comment]
Woops. I'll have it fixed when I get back home. (Hour or two).

**Comment by Black-Light** [comment]
Cool, thanks for all the updates

**Comment by seanegoodwin** [comment]
Should be fixed now.
