### ISSUE TITLE
0.7.2 Thumbnails and feedback

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#44]
After opening 0.7.2 PV and adding my gallery folder again PV I found i was missing thumbnails for around 70% of my gallery. I then closed PV and tried deleting all the thumbnails PV had previously generated but now i have no thumbnails at all.

I have also noticed that PandaViewer is a LOT faster, changing page, searching etc is instant now! It seemed to be getting slower over the previous versions (3-8s)but now it's perfect. I'm hoping that this isn't just because there is missing thumbnails.

**Comment by seanegoodwin** [comment]
Should be fixed now. I suspect a lot of the speed increase was simply due to the thumbnails not working.

**Comment by Black-Light** [comment]
Confirmed that it's fixed but also after going through each page and generating thumbnails then closing and re-opening PV i can confirm that it is still a lot faster.

Changing page, searching and sorting takes around 0.5-1s and is instant after I have used it for awhile.
