### ISSUE TITLE
Check second image hash for meta-data if no results were found

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#46]
I added covers to a lot of galleries or changed the order of the cover images so PV had a proper looking thumbnail the problem with this is that it seems to break meta-data gathering because the hash is different. Almost all of these galleries second image is the one used on ex-h and searching for the second image should yield the proper result.

I'm not completely sure this how it works, feel free to close this if it's unrelated to the meta-data gathering being unsuccessful.

**Comment by seanegoodwin** [comment]
I'm not sure what you mean by break - can you explain?

I suspect the problem is that once a gallery is found, we don't ever try to relocate it. The redownload metadata option just downloads the metadata again without looking for it. Maybe there's a need for a "reset all" option.

**Comment by Black-Light** [comment]
Well I was unable to find meta-data for some galleries where i changed the first image in the folder to be a cropped version of the cover. I thought that this was because PV is searching the hash for the cover and since I changed it that was the reason why I couldn't gather meta-data. If this is not the case then please, close this issue.

That is why i was suggesting changing it so if there were no results found then trying the second image, but once again I have no idea how PV searches for Meta-data and how the hashes work.

**Comment by seanegoodwin** [comment]
Ah, sorry, I misunderstood. It does only use the cover (that is, the first
file) to search. trying the second file if the first doesn't bring any
results isn't an awful idea, but it does add extra time to the overall
search.

**Comment by Black-Light** [comment]
Well it would only need to check the second image if there were no results, and it seems to find results around 95% of the time, sure sometimes it gets the wrong result but even then it wouldn't need to try the second image unless there was actually zero results.

**Comment by Zuescho** [comment]
It is already ignoring FILTERED_FILES = ("hentairulesbanner", "credits", "recruit"), so any file with those names will not be hashed. (Version 0.7.4)

This should be you solution to the cover problem.

**Comment by Black-Light** [comment]
Well yeah but since it's a custom cover there needs to be an exception that begins with some of the beginning characters in the sorting method used by windows. If i renamed my covers to any of those three examples above they would be the last image in the folder not the first.

This is why I suggested "!cover" because ! is one of the first characters in the sorting method used, alternatively just ! or multiple would work.

**Comment by Zuescho** [comment]
ahh okay I get the problem, my files are mostly named in a different way because of this I would get problem with anything that used a "ignore the first file" method.

My files are not 0-12 but "Title 01" "Title 02" etc... 
If you get the idear.

**Comment by seanegoodwin** [comment]
We will now (next release) search the second image if no hits are found from the first.
