### ISSUE TITLE
Metadata collection runs without verifying if any credentials have been entered.

### ISSUE THREAD

**Issue by Triskov** [seanegoodwin/PandaViewer#47]
I forgot to put the credential information back in after it was reset in 0.7. I was running it to generate a log showing gallery problems for what and why stuff wasn't found and similar problems. There's wasn't any notification that anything went wrong. It was only after looking at the log and seeing 
BadCredentialsError ERROR BadCredentialsError raised with message Your user id/password hash combination is incorrect..
everywhere that I realized that it didn't actually do anything. Naturally, this would be more obvious for first time metadata collection.

This probably shouldn't be the case as it easily allows someone who isn't paying attention/is a new user to run metadata collection without even having an account and then later complaining that the program is useless because it didn't do anything, or that they didn't realize they had to sign into an account, or similar issues. As far as I can tell, it doesn't seem to have caused any other problems, but I haven't tried signing in and out to see if any problems were caused. I still have access though, which is what matters.  
I don't remember if this has always been the case, or if it previously popped up an error before. 
Other post incoming at some point.

**Comment by seanegoodwin** [comment]
This was a regression, it's fixed in the next release.
