### ISSUE TITLE
[Minor] Unable to give galleries with links custom names

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#50]
Seems like as soon as you hit save it gets the title from ex again and replaces what you entered.

**Comment by seanegoodwin** [comment]
I'm not seeing that at all - can you explain?

**Comment by Black-Light** [comment]
When changing the name of a gallery that has an ex link already and pressing save the name doesn't change. I am guessing this is because when you hit save PandaViewer just fetches the title again.

This isn't a recent issue, have had it since changing to the new framework.

**Comment by seanegoodwin** [comment]
Yeah, that doesn't happen at all for me. And we don't fetch the title ever
again.

Could you make a recording/send it?

**Comment by Black-Light** [comment]
Well i would imagine it would let you custom name galleries with links on 0.8 and 0.8.1 because of this issue: https://github.com/seanegoodwin/PandaViewer/issues/49

I can do make a recording though just give me a minute.

**Comment by Black-Light** [comment]
Can't seem to replicate it anymore, I'm unsure what was causing it but it seems to occur pretty randomly unsure if new versions are affected.

If i run into this again I will re-open this issue.
