### ISSUE TITLE
[Feedback Requested] Hide gallery information

### ISSUE THREAD

**Issue by seanegoodwin** [seanegoodwin/PandaViewer#52]
I've been playing around with some UI stuff and was wondering the following:

If you guys are browsing through stuff, will you generally look at the title/rating?

I ask because I'm thinking about hiding that information, unless you mouse over it. It would look something like this:
![untitled](https://cloud.githubusercontent.com/assets/1712653/9602433/917e1e10-5076-11e5-8326-b095b6d1350c.jpg)

There's a couple of reasons besides looks I'd want to do this. It allows for more space on the screen to be used by the galleries and not on "wasted" space. And believe it or not, roughly 50% of the initial page loading time is taken up rendering the title and star rating stuff.

Any thoughts?

**Comment by Meowmel** [comment]
I normally don't as I recognize the cover - and to admit it, 99% of the time don't care. I wouldn't mind if you're doing it like that.

**Comment by Triskov** [comment]
The rating is entirely irrelevant to me aside from it being used as sorting method to easily show which galleries don't have metadata. The name doesn't matter much to me.

**Comment by Zuescho** [comment]
well it would mean more space, so yeah. i always take a look at the name, but besides that i dont think i would really miss it

**Comment by Black-Light** [comment]
This is a good idea, it would be even better if you could choose to only hide the rating and the menu button though. Also Is that a new menu button I see?

**Comment by seanegoodwin** [comment]
> Also Is that a new menu button I can see?

Two new buttons, although both will probably be disabled on release.

**Comment by Black-Light** [comment]
The new UI looks and functions really well, the only thing I don't like is how it stretches galleries thumbnails this should be optional in my opinion. With the new overlay functionality I'm wondering if you would consider changing it's color from black to whatever category the gallery falls under https://github.com/seanegoodwin/PandaViewer/issues/39

**Comment by seanegoodwin** [comment]
I'm not sure about coloring the the overlay - I think it would make it hard to read and be cryptic or require the need for a color guide. I do plan on putting a text label where the dropdown button used to be.

As for the stretches, really what needs to happen is a change for the thumbnail generator to try and get an area with the correct size/aspect ratio without stretching it. That will take some work though.
