### ISSUE TITLE
[Uh Oh] Literally does nothing.

### ISSUE THREAD

**Issue by Triskov** [seanegoodwin/PandaViewer#53]
Version 0.8.3.1
Doesn't work for me.
Literally does nothing.
No logs created and doesn't appear in task manager for even the slightest time.
Alas for changes causing problems.
It can't be helped.

**Comment by Black-Light** [comment]
Confirmed

**Comment by seanegoodwin** [comment]
Not sure why this one is broken - it works on my end (unlike the last one).

I've uploaded a debug version under Version 0.8.3.1. Run it and send my any logs/anything in the files stdout.txt/stderr.txt.

**Comment by Triskov** [comment]
No logs created.
Contents of stderr
Traceback (most recent call last):
  File "Q:\zPrograms\PandaViewer\Program.py", line 11, in <module>
ImportError: LoadLibraryEx 'Q:\zPrograms\PandaViewer\PyQt5\QtGui.pyd' failed

Nothing in stdout.
QtGui.pyd does exist in that directory.

**Comment by seanegoodwin** [comment]
I uploaded a new build - try it again.

**Comment by Triskov** [comment]
Traceback (most recent call last):
  File "Q:\zPrograms\PandaViewer\Program.py", line 12, in <module>
ImportError: LoadLibraryEx 'Q:\zPrograms\PandaViewer\PyQt5\QtGui.pyd' failed

Well, at least it got to the next line.

**Comment by seanegoodwin** [comment]
Damnit. New build, try again. I'm really not sure why this is happening now.

**Comment by Triskov** [comment]
Just downloaded it again a minute ago and tried it out.
Still says the same as my previous message.

**Comment by Black-Light** [comment]
Getting the same message as above, i can see a lot of the dlls have changed moving the files from the old build that are not in the new build didn't help however so it doesn't seem to be a case of missing libraries.

**Comment by seanegoodwin** [comment]
Yeah, something went wrong when I upgraded some stuff and I'm trying to figure out what is causing this.

New build, I have some hope for this one.

**Comment by Triskov** [comment]
It works.

**Comment by seanegoodwin** [comment]
Great. I'll run another build with the console disabled and release that.
