### ISSUE TITLE
Version 0.9 Error on attempted opening

### ISSUE THREAD

**Issue by Triskov** [seanegoodwin/PandaViewer#58]
![error](https://cloud.githubusercontent.com/assets/12780404/10125828/d753db42-6547-11e5-88cb-a45824206f2d.jpg)
No logs created.
May be a problem on my end. Certainly wasn't the case before, so something has changed at least.

**Comment by seanegoodwin** [comment]
Try downloading and installing this: http://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe

Looks like the new version of Python uses a new version of Microsoft's runtimes. Great.

**Comment by Triskov** [comment]
Correctly opens and loads now.

**Comment by seanegoodwin** [comment]
I suppose I'll have to have a note that you have to have that installed now. My guess is that MS will eventually push it out through Windows update.
