### ISSUE TITLE
[BUG][REGRESSION] Titles with apostrophes get HTML escape sequences

### ISSUE THREAD

**Issue by awused** [seanegoodwin/PandaViewer#61]
With version 0.9.0 I've noticed that the titles of galleries with apostrophes have been getting &#39; in place of the apostrophes.

I imagine this happens with other special characters that get escaped.

**Comment by seanegoodwin** [comment]
Looks like I fixed this already, but it didn't go into the most recent release. I'll close the issue when the next release is available.
