### ISSUE TITLE
Chaika links error?

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#77]
I can't get any of the panda links to save in PV to gather tags, I'm not sure if i am missing something here.

```
(Chaika URL Here)  /gallery/****/
(Chaika URL Here) /archive/****/
```

Both of these do not work, removed chaika url for obvious reasons.

**Comment by seanegoodwin** [comment]
Please enter the EH/EX url from chaika instead and tell me if that works. EX keeps metadata avaiable via their API even for deleted galleries. The "Chaika support" was actually a misnomer as PV doesn't ever reach out to it.

**Comment by Black-Light** [comment]
Oh I see so this feature was only intended to search chaika for the ex/eh gallery link if PV couldn't find it? And not actually gather tags from the chaika website? If this is the case then please close this, I was under the impression that you could use the chaika galleries for tags.

I realize I can just use the ex/eh link from chaika for deleted galleries, I have been doing that all the time. Guess I just read the release notes wrong.
