### ISSUE TITLE
Further update

### ISSUE THREAD

**Issue by seanegoodwin** [seanegoodwin/PandaViewer#80]
Hi all,

Just a small update to confirm that I both have not died and that I plan on continuing work on the project. 

Right now I'm in a big and slow planning phase to try and eliminate a lot of the technical debt accrued (what are tests anyway?) as well plan for the future of the program.

**Comment by Meowmel** [comment]
Great to hear from you Seane and good to know that you are still belonging to the living. I still use PV and will surely use the reworked version + do lots of testing/reports/suggestions again.
