### ISSUE TITLE
[Question]How do I completely delete metadata?

### ISSUE THREAD

**Issue by combataran** [seanegoodwin/PandaViewer#81]
It's incorrectly labeling galleries as German/French/languages that I have not downloaded. I'd like to start over from a fresh build but deleting the folder doesn't seem to delete metadata.

**Comment by seanegoodwin** [comment]
If you want to delete all the the metadata, deleting the DB itself is the easiest way. It can be found at C:\Users\<USER>\.lsv\db.sqlite.

There haven't been any changes to how PV collects metadata though, so more than likely you will run into the same situation.
